
DOCUMENTS = [
    # Business
    {"text": "The stock market closed higher today driven by tech gains.", "category": "Business"},
    {"text": "Inflation rates have stabilized according to the latest central bank report.", "category": "Business"},
    {"text": "The merger between the two giant corporations was approved by regulators.", "category": "Business"},
    {"text": "Small businesses are struggling with rising supply chain costs.", "category": "Business"},
    {"text": "Investors are looking for safe havens amidst global economic uncertainty.", "category": "Business"},
    {"text": "The quarterly earnings report showed a significant increase in revenue.", "category": "Business"},
    {"text": "Cryptocurrency markets are experiencing high volatility this week.", "category": "Business"},
    {"text": "A new trade agreement was signed to boost exports between the nations.", "category": "Business"},
    {"text": "The CEO announced a strategic restructuring of the company.", "category": "Business"},
    {"text": "Oil prices have dropped due to increased production.", "category": "Business"},
    {"text": "Unemployment rates have hit a historic low this quarter.", "category": "Business"},
    {"text": "The federal reserve raised interest rates to combat inflation.", "category": "Business"},
    {"text": "Startups are finding it harder to secure venture capital funding.", "category": "Business"},
    {"text": "E-commerce sales continue to grow as consumer habits shift online.", "category": "Business"},
    {"text": "The manufacturing sector is showing signs of recovery.", "category": "Business"},
    {"text": "Global supply chains are still recovering from the pandemic disruptions.", "category": "Business"},
    {"text": "Real estate markets in major cities are cooling down.", "category": "Business"},
    {"text": "Tech companies are laying off employees to cut costs.", "category": "Business"},
    {"text": "The GDP growth forecast has been revised downwards for next year.", "category": "Business"},
    {"text": "Corporate tax rates are a subject of debate in the parliament.", "category": "Business"},
    {"text": "Consumer confidence index rose unexpectedly this month.", "category": "Business"},
    {"text": "Gold prices surged as investors sought stability.", "category": "Business"},
    {"text": "The automotive industry is shifting towards electric vehicle production.", "category": "Business"},
    {"text": "A leading bank has been fined for regulatory compliance failures.", "category": "Business"},
    {"text": "Marketing strategies are evolving with the rise of AI tools.", "category": "Business"},
    {"text": "The retail sector is preparing for the holiday shopping season.", "category": "Business"},
    {"text": "Investment in renewable energy projects has doubled.", "category": "Business"},
    {"text": "Shareholders are demanding more transparency in governance.", "category": "Business"},
    {"text": "The logistics company expanded its fleet to meet demand.", "category": "Business"},
    {"text": "Financial analysts predict a mild recession in the coming months.", "category": "Business"},
    {"text": "The tech giant unveiled its latest smartphone model today.", "category": "Business"},
    {"text": "Interest in sustainable investing is growing among millennials.", "category": "Business"},
    {"text": "A new startup unicorn has emerged in the fintech space.", "category": "Business"},
    {"text": "Business travel hasn't fully returned to pre-pandemic levels.", "category": "Business"},
    {"text": "The government announced tax breaks for small enterprises.", "category": "Business"},

    # Entertainment
    {"text": "The new blockbuster movie broke box office records on its opening weekend.", "category": "Entertainment"},
    {"text": "A famous singer announced a world tour starting next summer.", "category": "Entertainment"},
    {"text": "The award ceremony honored the best performances in television.", "category": "Entertainment"},
    {"text": "Fans are eagerly awaiting the release of the sequel to the popular game.", "category": "Entertainment"},
    {"text": "The celebrity couple was spotted vacationing in Italy.", "category": "Entertainment"},
    {"text": "A new streaming service is launching with exclusive content.", "category": "Entertainment"},
    {"text": "The music festival lineup includes top international artists.", "category": "Entertainment"},
    {"text": "Critics have praised the actor's performance in the new drama.", "category": "Entertainment"},
    {"text": "The reality TV show has been renewed for another season.", "category": "Entertainment"},
    {"text": "A legendary rock band is reuniting for a final concert.", "category": "Entertainment"},
    {"text": "The fashion week showcased the latest trends from top designers.", "category": "Entertainment"},
    {"text": "A popular book is being adapted into a television series.", "category": "Entertainment"},
    {"text": "The gaming convention attracted thousands of attendees.", "category": "Entertainment"},
    {"text": "An upcoming documentary explores the life of a famous artist.", "category": "Entertainment"},
    {"text": "The comedian's new special is now streaming online.", "category": "Entertainment"},
    {"text": "Social media influencers are reshaping the entertainment industry.", "category": "Entertainment"},
    {"text": "The theater production received a standing ovation on opening night.", "category": "Entertainment"},
    {"text": "A classic film is being remastered for a theatrical re-release.", "category": "Entertainment"},
    {"text": "The jazz festival will feature performances by renowned musicians.", "category": "Entertainment"},
    {"text": "A new superhero movie is in production with a star-studded cast.", "category": "Entertainment"},
    {"text": "The art gallery is hosting an exhibition of modern sculptures.", "category": "Entertainment"},
    {"text": "Video game sales have surpassed movie box office revenue.", "category": "Entertainment"},
    {"text": "The pop star's new album topped the charts within hours.", "category": "Entertainment"},
    {"text": "A famous director is working on a sci-fi trilogy.", "category": "Entertainment"},
    {"text": "The opera house is undergoing major renovations.", "category": "Entertainment"},
    {"text": "A viral video has launched the career of a young musician.", "category": "Entertainment"},
    {"text": "The film festival awarded the Golden Palm to an indie movie.", "category": "Entertainment"},
    {"text": "Celebrity gossip magazines are speculating about a royal wedding.", "category": "Entertainment"},
    {"text": "A new theme park attraction is based on a popular franchise.", "category": "Entertainment"},
    {"text": "The orchestra performed a symphony by Beethoven.", "category": "Entertainment"},
    {"text": "Stand-up comedy clubs are seeing a resurgence in popularity.", "category": "Entertainment"},
    {"text": "The dance troupe is touring across the country.", "category": "Entertainment"},
    {"text": "A biographical film about the musician is in the works.", "category": "Entertainment"},
    {"text": "The magician stunned the audience with his latest illusion.", "category": "Entertainment"},
    {"text": "Online gaming communities are growing rapidly.", "category": "Entertainment"},

    # Health
    {"text": "Regular exercise is essential for maintaining cardiovascular health.", "category": "Health"},
    {"text": "A balanced diet rich in fruits and vegetables prevents chronic diseases.", "category": "Health"},
    {"text": "Doctors recommend getting a flu shot every year.", "category": "Health"},
    {"text": "New research suggests a link between sleep and mental health.", "category": "Health"},
    {"text": "The hospital is expanding its emergency department.", "category": "Health"},
    {"text": "Mental health awareness is increasing in workplaces.", "category": "Health"},
    {"text": "High blood pressure is a silent killer if left untreated.", "category": "Health"},
    {"text": "Yoga and meditation can help reduce stress and anxiety.", "category": "Health"},
    {"text": "A breakthrough in cancer treatment offers hope to patients.", "category": "Health"},
    {"text": "Vaccination campaigns are crucial for herd immunity.", "category": "Health"},
    {"text": "Drinking enough water is important for overall well-being.", "category": "Health"},
    {"text": "The pandemic highlighted the importance of public health systems.", "category": "Health"},
    {"text": "Diabetes management requires monitoring blood sugar levels.", "category": "Health"},
    {"text": "Telemedicine is becoming a popular way to consult doctors.", "category": "Health"},
    {"text": "Vitamin D deficiency is common during winter months.", "category": "Health"},
    {"text": "Smoking is a leading cause of lung cancer and heart disease.", "category": "Health"},
    {"text": "Pediatricians advise limiting screen time for children.", "category": "Health"},
    {"text": "Antibiotic resistance is a growing global health threat.", "category": "Health"},
    {"text": "Regular check-ups can detect health issues early.", "category": "Health"},
    {"text": "Obesity rates are rising in many developed countries.", "category": "Health"},
    {"text": "Meditation apps are helping people manage their mental state.", "category": "Health"},
    {"text": "A new virus strain has been identified by scientists.", "category": "Health"},
    {"text": "Physical therapy helps patients recover from injuries.", "category": "Health"},
    {"text": "Nutritional supplements should not replace a healthy diet.", "category": "Health"},
    {"text": "Sleep apnea can lead to serious health complications.", "category": "Health"},
    {"text": "The benefits of breastfeeding for infants are well documented.", "category": "Health"},
    {"text": "Chronic pain management often requires a multidisciplinary approach.", "category": "Health"},
    {"text": "Seasonal allergies affect millions of people every spring.", "category": "Health"},
    {"text": "Hand hygiene is the most effective way to prevent infection.", "category": "Health"},
    {"text": "Heart disease is the leading cause of death globally.", "category": "Health"},
    {"text": "The pharmaceutical company is testing a new drug for Alzheimer's.", "category": "Health"},
    {"text": "Public health officials are monitoring the spread of the disease.", "category": "Health"},
    {"text": "Healthy eating habits should be established in childhood.", "category": "Health"},
    {"text": "Stress management techniques include deep breathing exercises.", "category": "Health"},
    {"text": "The clinic offers free screenings for skin cancer.", "category": "Health"},

    # Additional Business
    {"text": "The company announced strong earnings for the fiscal year.", "category": "Business"},
    {"text": "Analysts predict stock prices will rise next quarter.", "category": "Business"},
    {"text": "Interest rates impact borrowing costs for businesses.", "category": "Business"},
    {"text": "Apple is a leading tech giant in the stock market.", "category": "Business"},
    {"text": "Inflation affects consumer spending power.", "category": "Business"},

    # Additional Entertainment
    {"text": "The studio announced the release date for the new movie.", "category": "Entertainment"},
    {"text": "The actor's performance was praised by critics.", "category": "Entertainment"},
    {"text": "The band released a new album yesterday.", "category": "Entertainment"},
    {"text": "Tickets for the concert sold out in minutes.", "category": "Entertainment"},
    {"text": "The film festival showcases independent cinema.", "category": "Entertainment"},

    # Additional Health
    {"text": "Flu vaccination rates have dropped significantly.", "category": "Health"},
    {"text": "Doctors advise getting vaccinated against the flu.", "category": "Health"},
    {"text": "Heart disease is a major health concern worldwide.", "category": "Health"},
    {"text": "Flu vaccination rates are rising among the elderly.", "category": "Health"},
    {"text": "Low vaccination rates can lead to outbreaks.", "category": "Health"},
    {"text": "Regular exercise lowers the risk of diabetes.", "category": "Health"},

    {"text": "A healthy diet boosts the immune system.", "category": "Health"},
]


def get_documents():
    return DOCUMENTS
